### ISSUE TITLE
Google Earth Link

### ISSUE THREAD

**Issue by oowhowhatoo** [cds-astro/fitsrs#2]
https://earth.app.goo.gl/?apn=com.google.earth&isi=293622097&ius=googleearth&link=https%3a%2f%2fearth.google.com%2fweb%2f%4029.79237089,-120.64509147,-28070.20779679a,63191992.45631219d,35y,0h,0t,0r

**Comment by bmatthieu3** [comment]
I close the issue as well. Feel free to reopen a new one with a more explicit content.
