### ISSUE TITLE
UB in data reading

### ISSUE THREAD

**Issue by RReverser** [cds-astro/fitsrs#5]
I noticed the library crashing on some of my input files, and after looking at the code it became clear why: this part is explicitly UB. https://github.com/cds-astro/fitsrs/blob/ea2b86ebc39a372bcc7da812a3c72e823ea2345f/src/hdu/data/image.rs#L41-L44

In Rust it's prohibited to convert from immutable references to mutable ones, even in `unsafe` block, and it will lead to miscompilations. That's why the marker code required `unsafe` in the first place - because compiler was trying to point at invalid usage. `unsafe` should never be used to work around UB warnings.

The correct fix would be to either accept mutable references in the first place, or update all places that use them to immutable references instead. Where necessary, data has to be cloned - anything to avoid creating accidental aliasing of data that compiler assumes to never be aliased.

**Comment by RReverser** [comment]
Offtop, but trying to clone the repo to e.g. run its own tests currently fails with:

> Downloading samples/fits.gsfc.nasa.gov/Astro_UIT.fits (865 KB)
Error downloading object: samples/fits.gsfc.nasa.gov/Astro_UIT.fits (3110c73): Smudge error: Error downloading samples/fits.gsfc.nasa.gov/Astro_UIT.fits (3110c73eebbdd479b9a51cb275f18650f17d22b818713562b6e27d873e128530): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by tikk3r** [comment]
Running into this same issue (accidentally opened #7 as a duplicate). Using some editor hints, it builds for me if I change

```Rust
let x_mut_ref = &mut *x_ptr;
```
to

```Rust
let x_mut_ref = &mut *x_ptr.as_mut().unwrap();
```
and it seems fine for my use case, but I am not sure if that is the proper fix.

**Comment by bmatthieu3** [comment]
I fixed the compilation issue by using a UnsafeCell. @RReverser do you have an example input file where it is crashing ?

**Comment by RReverser** [comment]
Sorry, no. It's been a while and, after seeing those UB usages, I decided to use alternative libraries.

**Comment by bmatthieu3** [comment]
Ok no problems. I will close this issue then. Please do not hesitate to reopen it if you experience similar issues.

**Comment by RReverser** [comment]
Sorry but the UB is still there regardless. This is absolutely not the correct usage of `unsafe` in Rust and can be miscompiled easily in any future version or on the wrong data.

**Comment by kornelski** [comment]
You don't need `UnsafeCell` and all the other hacks.

https://github.com/cds-astro/fitsrs/blob/8e4040c80b3e6899b7ef7060aea87cdae68b37b3/src/hdu/data/image.rs#L33

this `get_ref`  could be `get_mut` that gives you safe mutable access.

You're probably struggling calling  ` let pos = self.position() as usize;` afterwards while all of `self` is borrowed exclusively, but this can be solved simply by moving `self.position() ` line up before the `get_mut()` call, or you can call `get_mut()` even later in smaller scopes inside the `match`.

**Comment by bmatthieu3** [comment]
I had no choice of allocating a new vector to contains the data values swapped from BigEndian scheme (as the FITS standard stores its data...). I do not allocate anything if the BITPIX is 8 because it is Endian independant and for that particular case only I can directly return the slice view on memory and I do not have to allocate a new vector.

**Comment by RReverser** [comment]
@bmatthieu3 Thanks for fixing!

As for allocation concerns, I think one way to step aside that issue could be to use the `zerocopy` crate which has endian-aware wrappers for all primitives built-in, and might make parsing/serialization a lot more pleasant with `derive`s: https://docs.rs/zerocopy/latest/zerocopy/byteorder/index.html

It might, however, make working with the resulting data more awkward since those primitives will now need manual conversion, so idk if it's worth it just to avoid allocations.
