### ISSUE TITLE
Readme example confusion

### ISSUE THREAD

**Issue by tikk3r** [cds-astro/fitsrs#6]
Apologies for the unclear issue title, but I'm trying out the "files that can fit in memory" example in the readme and I can't quite get it to work on a FITS image I have. It seems to never enter the while loop and extract the image data. I am also quite new to Rust, which makes it a bit harder for me to figure out, but as I understand

```Rust
    let mut hdu_ext = hdu.next();
```

is ran to obain the first entry and kickstart the looping? In my case it seems it returns `None` however and thus never enters the subsequent while loop:

```Rust
dbg!(&hdu_ext);

[src/main.rs:27:5] &hdu_ext = Ok(
    None,
)
```

Just printing out the hdu seems to have something there. Given that I'm new to Rust, I feel I am simply missing something or misunderstanding the example? Any help would be appreciated.

```Rust
dbg!(hdu);
[src/main.rs:25:5] &hdu = PrimaryHDU(
    HDU {
        header: Header {
            cards: {
                [
                    79,
                    66,
                    83,
                    69,
                    82,
                    86,
                    69,
                    82,
                ]: String(
                    "AK461   ",
                ),
<snip>
        data: Data {
            reader: Cursor {
                inner: [
                    83,
                    73,
                    77,
            num_bytes_read: 262144,
            data: F32(
                [
                    -0.02798142,
                    -0.02848068,
                    -0.027634708,
                    -0.026519012,
                    -0.027033258,
                    -0.03116115,
                ],
            ),
        },
    },
)


```

**Comment by bmatthieu3** [comment]
Hi @tikk3r ,

Which fits file are you opening ? The call to hdu.next() returns the next HDU extension i.e. if your fits file has no extensions then it will not found some. hdu stores the primary HDU so you will have your image there.

**Comment by tikk3r** [comment]
> Hi @tikk3r ,
> 
> Which fits file are you opening ? The call to hdu.next() returns the next HDU extension i.e. if your fits file has no extensions then it will not found some. hdu stores the primary HDU so it seems to have the image there.

It's just a local FITS image of my data. I thought the image/primary HDU would fall under the extensions, but maybe I just misunderstood the FITS format in that regard then?

**Comment by tikk3r** [comment]
I think this was ultimately just some confusion on my end, so closing this.
